### PR TITLE
Fix all cert lint errors

### LINKED ISSUE #74: Check certificates against zlint.
We should check our certificates against [zlint](https://github.com/zmap/zlint) to make sure we are constructing the certificates correctly.

### PR DESCRIPTION
**Pull request by sree-revoori1**
1. Truncate SerialNumber to 64 bits
2. Count unused bits in KeyUsage
3. Add SubjectKeyIdentifier extension
4. Add AuthorityKeyIdentifier extension
5. Make cert lint errors/warns fatal in CI
6. Update caliptra-cfi revision

fixes #74

### CODE REVIEW

File: verification/testing/certifyKey.go [hunk 1]
```diff
@@ -341,6 +344,10 @@ func checkCertifyKeyExtensions(t *testing.T, extensions []pkix.Extension, flags
 	checkCertifyKeyBasicConstraints(t, extensions, flags)
 	checkCertifyKeyExtendedKeyUsages(t, extensions, bc.IsCA)
 	checkCertifyKeyTcgUeidExtension(t, extensions, label)
+	if IsX509 {
+		checkCertifyKeySubjectKeyIdentifierExtension(t, extensions, bc.IsCA, pubkey)
+		checkCertifyKeyAuthorityKeyIdentifierExtension(t, extensions, bc.IsCA, pubkey)
```
Comment (jhand2) [inline verification/testing/certifyKey.go:349]: If I understand RFC 5280 correctly, I think the AKI is supposed to use the Issuer's public key

File: dpe/src/commands/certify_key.rs [hunk 2]
```diff
@@ -109,10 +109,12 @@ impl CommandExecution for CertifyKeyCmd {
         let mut subj_serial = [0u8; DPE_PROFILE.get_hash_size() * 2];
         env.crypto
             .get_pubkey_serial(DPE_PROFILE.alg_len(), &pub_key, &mut subj_serial)?;
+        // The serial number of the subject can be at most 64 bytes
+        let truncated_subj_serial = &subj_serial[..64];
```
[the remark this answers is not in the document]
Comment (sree-revoori1) [reply dpe/src/commands/certify_key.rs:113]: We can still do the truncating right? I added the check to the exclusion list already.

File: verification/testing/certifyKey.go (hunk 1 above)
Comment (sree-revoori1) [reply verification/testing/certifyKey.go:349]: Done, added a function to the platform to retrieve the issuing cert's SubjectKeyIdentifier.

**Review by jhand2 — APPROVED** [review]
